<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Inicia sesión</h1>
    <form action="index.php?c=user" method="post">
        <input type="text" name="username" placeholder="nombre de usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="submit" value="Iniciar sesión">
    </form>

    <br><br>
    <a href="index.php?c=user&register=1">Registrar nuevo usuario</a>
</body>

</html>