<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Registrate</h1>
    <form action="index.php?c=user" method="post">
        <input type="text" name="username" placeholder="nombre de usuario">
        <input type="password" name="password" placeholder="contraseña">
        <input type="password" name="password2" placeholder="repite contraseña">
        <input type="submit" value="Registrarse">
    </form>
</body>

</html>